### ISSUE TITLE
Some of the challenge tags not getting updated to the member profile

### ISSUE THREAD

**Issue by SathyaJayabal** [topcoder-platform/skills-etl#10]
Tested with a challenge with three tags. On running the skills-etl, one of the tag was added to the member aggregated skills table, but not the other two. The other two skills were present in the tags static text file. Need more investigation on why the two skills were skipped.

test challenge:
legacy id: 30055274
https://www.topcoder-dev.com/challenges/cca46fca-b18a-4bb1-b999-43b80fb56049

member: TonyJ (8547899)

skill added successfully :Node.js
skills skipped: Servlet, Applet

**Comment by sushilshinde** [comment]
resolved
