### ISSUE TITLE
The table being created as MemberAggregatedSkills should be ChallengeSkills

### ISSUE THREAD

**Issue by sayantandey** [topcoder-platform/skills-etl#4]
This [query](https://github.com/topcoder-platform/skills-etl/blob/develop/src/input/userChallengeSkills.js#L36) corresponds to the challenge skill collector job used in the main [Hadoop job repo](https://github.com/appirio-tech/ap-emr-skills/blob/dev/src/main/resources/scripts/sqoop.challengeSkills.txt#L15).

**Comment by sushilshinde** [comment]
Totally makes sense
